# Generated by Django 3.0.5 on 2020-04-14 04:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200413_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
